#						12/11/2018


#MySQL Tutorial - MySQL By Examples for Beginners.htm
#2.10
# mysql> source ~/Documents/Neo.sql

INSERT INTO IP VALUES (1,'EMPTY','EMPTY');

INSERT INTO Alarm VALUES (1,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),   
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0),
                         (null,'EMPTY',0,0,0);


INSERT INTO Lights VALUES ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY');


INSERT INTO irrigation VALUES ('EMPTY','EMPTY','EMPTY'),
                              ('EMPTY','EMPTY','EMPTY'),
                              ('EMPTY','EMPTY','EMPTY'),
                              ('EMPTY','EMPTY','EMPTY'),
                              ('EMPTY','EMPTY','EMPTY');

INSERT INTO plugs VALUES  ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),

                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),

                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),

                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),

                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY'),
                          ('EMPTY','EMPTY','EMPTY','EMPTY');


INSERT INTO curtain VALUES ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),

                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),

                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),

                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),

                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY'),
                           ('EMPTY','EMPTY','EMPTY','EMPTY');

INSERT INTO Cam_ip VALUES  ('EMPTY','EMPTY'),
                           ('EMPTY','EMPTY'),
                           ('EMPTY','EMPTY'),
                           ('EMPTY','EMPTY'),
                           ('EMPTY','EMPTY'),

                           ('EMPTY','EMPTY'),
                           ('EMPTY','EMPTY'),
                           ('EMPTY','EMPTY'),
                           ('EMPTY','EMPTY'),
                           ('EMPTY','EMPTY');

INSERT INTO Motivation VALUES ('EMPTY');
